apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: project8-dev-success-rate
  namespace: project8-dev
spec:
  args:
    - name: service-name
      value: project8
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(
              rate(
                http_requests_total{
                  service="{{args.service-name}}",
                  status!~"5.."
                }[1m]
              )
            )
            /
            sum(
              rate(
                http_requests_total{
                  service="{{args.service-name}}"
                }[1m]
              )
            )

