apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: project8-dev-success-rate
  namespace: project8-dev
spec:
  metrics:
    - name: restart-count
      interval: 30s
      count: 5
      failureLimit: 1
      successCondition: len(result) > 0 && result[0] == 0
      failureCondition: len(result) == 0 || result[0] > 0
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(increase(kube_pod_container_status_restarts_total{namespace="project8-dev"}[2m]))

