apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: project8-dev-success-rate
  namespace: project8-dev
spec:
  args:
    - name: app
      value: project8-dev
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      # Index error on empty return value
      #successCondition: result[0] >= 0.95
      successCondition: len(result) > 0 && result[0] >= 0.95
      failureCondition: len(result) == 0

      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(
              rate(
                http_requests_total{
                  service="{{args.app}}",
                  status!~"5.."
                }[1m]
              )
            )
            /
            sum(
              rate(
                http_requests_total{
                  service="{{args.app}}"
                }[1m]
              )
            )

