apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project8-dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: rollout-analysis-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: project8-nginx-rollout

